server:
  servlet:
    context-path: /
  port: 9527

spring:
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
  resources:
    static-locations: classpath:/static/,classpath:/templates/

# distkv config
distkv:
  server-address: distkv://127.0.0.1:8082

# custom jwt expire time
jwt:
  token:
    expire-time: 1800000  # 30minute
  refresh-token:
    expire-time: 2592000000 # 30day
