
name: distkv-cloud build

on:
  pull_request:
    branches:
      -master
jobs:
  build:
    runs-on: ubantu-lastest
    steps:
      - name: user checkout@v2 action
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: package distkv-cloud
        run: mvn clean install -DskipTests
      - name: distkv-cloud test case result
        run: mvn test
      - name: report the result of code coverage
        run: bash <(curl -s https://codecov.io/bash)
